source 'https://github.com/ZHK1024/LLSpecs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs'

use_frameworks!

platform :ios, '11.0'

target 'LLCalendar_Example' do
  pod 'LLCalendar', :path => '../'

  target 'LLCalendar_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
